In [1]:
!pip install numpy

In [2]:
import numpy as np
arr1= np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
#1d array
arr2= np.array([1,2,3,4,5])
arr2.reshape(1,5)       #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [9]:
#2d array
arr2=np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]]
(2, 6)


In [15]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
#In-built functions
np.ones((3,4))  #it will create 2d array with 3 rows and 4 columns where all the values will be 1



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# identity matrix
np.eye(3)
#diagonal elements are 1 rest all will be 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of Dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [21]:
#Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element Wise addition
print("Addition:", arr1+arr2)

# Element wise Substraction
print("Substraction:", arr1-arr2)

# Element wise Multiplication
print("Multiplication:", arr1*arr2)

# Element wise Division
print("Division:", arr1/arr2)


Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
# Universal Function(ufuncs)
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

#natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
# array slicing and Indexing

arr=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
arr[0][0]

np.int64(1)

In [31]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [34]:
print(arr[0][0])
print(arr[1:])

1
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print(arr[0][0])
print(arr[0:2])

1
[[1 2 3 4]
 [5 6 7 8]]


In [36]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [37]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [39]:
# Modify array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [41]:
arr[1:]=100
print(arr)

#all the rows apart from the first one will be 100

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [44]:
# Statistical concepts --> Normalization
# --> to have a mean of 0 and a standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean= np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data-mean) / std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [45]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [47]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data>5
#data[(data>=5) & (data<=8)]

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[data>5]

array([ 6,  7,  8,  9, 10])

In [49]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])